// <auto-generated />
using System;
using Fruit.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fruit.Data.Migrations
{
    [DbContext(typeof(FruitShoppingDbContext))]
    [Migration("20210829004109_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fruit.Domain.Entities.FruitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId")
                        .IsUnique();

                    b.ToTable("Fruit");
                });

            modelBuilder.Entity("Fruit.Domain.Entities.FruitInventoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FruitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FruitInventory");
                });

            modelBuilder.Entity("Fruit.Domain.Entities.FruitPictureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("FruitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("FruitId");

                    b.ToTable("FruitPicture");
                });

            modelBuilder.Entity("Fruit.Domain.Entities.Sell.SellEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sell");
                });

            modelBuilder.Entity("Fruit.Domain.Entities.Sell.SellItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FruitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SellId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SellId");

                    b.ToTable("SellItem");
                });

            modelBuilder.Entity("Fruit.Domain.Entities.FruitEntity", b =>
                {
                    b.HasOne("Fruit.Domain.Entities.FruitInventoryEntity", "Inventory")
                        .WithOne("Fruit")
                        .HasForeignKey("Fruit.Domain.Entities.FruitEntity", "InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Fruit.Domain.Entities.FruitPictureEntity", b =>
                {
                    b.HasOne("Fruit.Domain.Entities.FruitEntity", "Fruit")
                        .WithMany("Pictures")
                        .HasForeignKey("FruitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fruit");
                });

            modelBuilder.Entity("Fruit.Domain.Entities.Sell.SellItemEntity", b =>
                {
                    b.HasOne("Fruit.Domain.Entities.FruitEntity", "Fruit")
                        .WithMany("SellItems")
                        .HasForeignKey("SellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fruit.Domain.Entities.Sell.SellEntity", "Sell")
                        .WithMany("SellItems")
                        .HasForeignKey("SellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fruit");

                    b.Navigation("Sell");
                });

            modelBuilder.Entity("Fruit.Domain.Entities.FruitEntity", b =>
                {
                    b.Navigation("Pictures");

                    b.Navigation("SellItems");
                });

            modelBuilder.Entity("Fruit.Domain.Entities.FruitInventoryEntity", b =>
                {
                    b.Navigation("Fruit");
                });

            modelBuilder.Entity("Fruit.Domain.Entities.Sell.SellEntity", b =>
                {
                    b.Navigation("SellItems");
                });
#pragma warning restore 612, 618
        }
    }
}
